---
# tasks file for add_new_worker_node
- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['masters'][0] }}"

- name: Set join command
  set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout_lines[0] }}"

- name: Run kubeadm join
  shell: "{{ kubeadm_join }} >> node_joined.log"
  args:
    chdir: /home/andrey
    creates: node_joined.log
