---
# vars file for install_k8s_dependencies
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
kubernetes:
  - kubelet=1.29.*
  - kubeadm=1.29.*
  - kubectl=1.29.*
